import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    fileParallelism: false,
    maxConcurrency: 1,
    include: [
      "src/**/*.test.ts",
      "src/**/*.test.tsx",
      "src/**/*.spec.ts",
      "src/**/*.spec.tsx",
      "apps/**/*.test.ts",
      "apps/**/*.test.tsx",
      "apps/**/*.spec.ts",
      "apps/**/*.spec.tsx",
    ],
    exclude: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/coverage/**",
      "**/convex/_generated/**",
      "**/*.generated.*",
      "**/*.gen.*",
      "**/*.d.ts",
      "**/*.config.*",
      "**/vitest.config.ts",
      "tests/**",
      // Mobile Expo tests run under apps/mobile Jest config, not root Vitest.
      "apps/mobile/__tests__/smoke.test.ts",
      "src/app/tasks/create-task-form.test.ts",
      "src/components/layout/shell-signals.test.tsx",
      "src/components/layout/top-bar.test.tsx",
      "src/components/review/trend-bar-chart.test.tsx",
      "src/components/review/session-heatmap.test.tsx",
      "src/components/tasks/task-due-date-label.test.tsx",
      "src/components/tasks/task-kanban-card.test.ts",
      "src/components/tasks/task-reminder-panel.test.tsx",
      "src/components/tasks/task-saved-views-panel.test.ts",
      "src/components/today/today-task-card.test.ts",
      "src/lib/services/task-service.test.ts",
      "src/lib/services/task-service-archive.test.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov", "json"],
      reportsDirectory: "coverage",
      exclude: [
        "**/node_modules/**",
        "**/.next/**",
        "**/dist/**",
        "**/coverage/**",
        "**/convex/_generated/**",
        "**/*.generated.*",
        "**/*.gen.*",
        "**/*.d.ts",
        "**/*.config.*",
        "**/tests/**",
        "**/*.test.*",
        "**/*.spec.*",
      ],
    },
    alias: {
      "@": path.resolve(__dirname, "src"),
      "node:test": path.resolve(__dirname, "src/test-support/vitest-node-test.ts"),
      "server-only": path.resolve(__dirname, "src/test-support/server-only.ts"),
    },
  },
});
